---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  selector:
    matchLabels:
      app: cart-deployment
  template:
    metadata:
      labels:
        app: cart-deployment
    spec:
      containers:
      - name: cart
        image: 375586205616.dkr.ecr.ap-northeast-2.amazonaws.com/demo-cart-backend:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: cart-redis