apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-commerce
resources:
  - product-service.yaml
  - product-configmap.yaml
  - product-secret.yaml
  - product-deployment.yaml